# Generated by Django 4.1.5 on 2023-03-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='quen',
            new_name='queue',
        ),
    ]
