# Generated by Django 4.1.5 on 2023-03-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_photo_subject_homewok'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homewok',
            new_name='Homework',
        ),
    ]
