# Generated by Django 4.1.7 on 2023-03-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_homewok_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_class',
            new_name='subject_classes',
        ),
    ]
